### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by junyuanz123** [justinjung04/universal-boilerplate#8]
Hi Justin,

Nice tutorial, it's very helpful! I am new to server side rendering, so I have a question, in the `middleware.js` we are still using `<script src='bundle.js'></script>`, is there any reason we are doing that? I mean if we are downloading the production webpack bundle, then what's the difference between server side rendering and client side rendering?

**Comment by justinjung04** [comment]
The only difference is that the server returns html tags as a string when it gets a request. Then it would download the webpack bundle, which hooks event handlers to those html tags. We go through this hassle for search engine optimization, so that search engines can read those html tags and know what our website contains.

**Comment by junyuanz123** [comment]
Thank you so much!
